name: gcloud
version: 112.0.0
summary: Google Cloud SDK
description: Command-line interface for Google Cloud Platform products and services

confinement: strict
grade: stable

apps:
    gcloud:
        command: gcloud
        plugs:
            - network
            - network-bind
            - docker

parts:
    google-cloud-sdk:
        plugin: dump
        source: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-112.0.0-linux-x86_64.tar.gz
    python:
        plugin: nil
        stage-packages:
            # Get python packed into the snap as well.
            - python
    docker:
        plugin: dump
        source: https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
        organize:
            # Move the docker binary to the bin/ directory in the resulting snap.
            docker: bin/docker
        snap:
            # Just include the docker CLI.
            - bin/docker
